[workspace]
members = ["crates/*", "crates/*/fuzz"]

[profile.release]
lto = "thin"

[workspace.dependencies]
chik-bls = "0.29.0"
chik-pos2 = { path = "crates/chik-pos2", version = "0.6.0" }
blake3 = "1.8.2"
cc = { version = "1.2.16", features = ["parallel"] }
rstest = "0.26.1"
serde = { version = "1.0.219", features = ["derive"] }
serde-big-array = "0.5.1"
clap = "4.5.38"
sha2 = "0.10.9"
hex = "0.4.3"
arbitrary = "1.4.2"
criterion = { version = "0.5.1", default-features = false }
