[package]
name = "chik-pos2"
version = "0.5.0"
edition = "2024"
license = "Apache-2.0"
description = "A library for creating plots, validating proofs of space, farming partial proofs and solving proofs. Using Chik proof of space v2"
authors = [
    "Arvid Norberg <arvid@chiknetwork.com>",
    "Harold Brenes <h.brenes@chiknetwork.com>",
    "Nick Halper <n.halper@chiknetwork.com>"
]
homepage = "https://github.com/Chik-Network/pos2/crates/chik-po2"
repository = "https://github.com/Chik-Network/pos2/crates/chik-pos2"

[lib]
bench = false

[features]
arbitrary = ["dep:arbitrary"]

[dependencies]
serde = { workspace = true }
serde-big-array = { workspace = true }
arbitrary = { workspace = true, features = ["derive"], optional = true }

[build-dependencies]
cc = { workspace = true }

[dev-dependencies]
criterion = { workspace = true }
rstest = { workspace = true }

[[bench]]
name = "pos2_bench"
harness = false
