[package]
name = "chik-pos2-tools"
version = "0.6.0"
edition = "2024"
license = "Apache-2.0"
description = "Testing tools for chik-pos2"
authors = [
    "Arvid Norberg <arvid@chiknetwork.com>",
]
homepage = "https://github.com/Chik-Network/pos2/crates/chik-po2-tools"
repository = "https://github.com/Chik-Network/pos2/crates/chik-pos2-tools"

[dependencies]
chik-pos2 = { workspace = true }
sha2 = { workspace = true }
clap = { workspace = true, features = ["derive"] }
hex = { workspace = true }

[[bin]]
name = "test-prover"
test = false
bench = false
