name: Format

on:
  push:
    branches:
      - main1
    tags:
      - "**"
  pull_request:
    branches:
      - "**"

concurrency:
  group: ${{ github.event_name == 'pull_request' && format('{0}-{1}', github.workflow_ref, github.event.pull_request.number) || github.run_id }}
  cancel-in-progress: true

jobs:
  check-formatting:
  runs-on: ubuntu-latest
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: clang-format
      run: find src tests -iname '*.h' -o -iname '*.cpp' -o -iname '*.hpp' | clang-format --files=/dev/stdin --dry-run
